import { BookOpen, Bookmark, Check, ChevronDown, ExternalLink } from "lucide-react";
import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import type { ResearchPaper } from "@/lib/evidence-model";
export function ResearchPaperCard({ paper, onSave }: { paper: ResearchPaper; onSave?: (paper: ResearchPaper) => void }) {
  const [open, setOpen] = useState(false); const passage = paper.passages[0];
  return <article className="paper-result"><p className="meta-label text-primary">{paper.studyType}</p><Link to="/app/paper/$id" params={{ id: paper.id }} className="mt-2 block font-serif text-xl leading-snug hover:text-primary">{paper.title}</Link><p className="mt-2 text-sm text-muted-foreground">{paper.authors.slice(0, 3).join(", ")}{paper.authors.length > 3 ? " et al." : ""}</p><p className="mt-1 text-sm text-muted-foreground">{paper.journal} · {paper.year ?? "n.d."}</p><p className="mt-4 line-clamp-2 text-sm leading-6">{passage?.text ?? paper.abstract}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 border-t pt-3 text-xs text-muted-foreground">{paper.participants && <span>{paper.participants}</span>}{paper.studiesIncluded && <span>{paper.studiesIncluded} studies</span>}<span className="inline-flex items-center gap-1 text-success"><Check className="size-3" />Peer reviewed</span></div><div className="mt-4 flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><Link to="/app/paper/$id" params={{ id: paper.id }}><BookOpen />Read paper</Link></Button><Button variant="outline" size="sm" onClick={() => setOpen((v) => !v)}><ChevronDown className={open ? "rotate-180" : ""} />View evidence</Button><Button variant="ghost" size="sm" onClick={() => onSave?.(paper)}><Bookmark />Save</Button><Button asChild variant="ghost" size="icon"><a href={paper.url} target="_blank" rel="noreferrer noopener" aria-label="Open original paper"><ExternalLink /></a></Button></div>{open && <blockquote className="mt-4 border-l-2 border-primary bg-secondary p-4 text-sm leading-6">“{passage?.text ?? paper.abstract}”</blockquote>}</article>;
}
