import { ArrowRight, SlidersHorizontal } from "lucide-react";
import { useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
const TYPES = ["Meta-analysis", "Systematic review", "RCT", "Observational"];
export function SearchForm({ initial = "", busy = false, onSearch, compact = false }: { initial?: string; busy?: boolean; onSearch: (q: string) => void; compact?: boolean }) {
  const [q, setQ] = useState(initial); const [filters, setFilters] = useState(false);
  const submit = (e: FormEvent) => { e.preventDefault(); if (q.trim().length >= 3) onSearch(q.trim()); };
  return <div className="w-full"><form onSubmit={submit} className="search-frame"><Input value={q} onChange={(e) => setQ(e.target.value)} aria-label="Research question" placeholder="Ask a research question…" className={compact ? "h-11 border-0 bg-transparent text-base shadow-none" : "h-14 border-0 bg-transparent text-base shadow-none md:text-lg"} /><Button type="submit" disabled={busy || q.trim().length < 3} size={compact ? "default" : "lg"}>{busy ? "Searching…" : <>Search <ArrowRight /></>}</Button></form><div className="mt-3 flex flex-wrap items-center gap-2"><Button variant="ghost" size="sm" onClick={() => setFilters((v) => !v)}><SlidersHorizontal /> {filters ? "Hide filters" : "Filters"}</Button>{["All research", "Clinical trials", "Reviews", "Meta-analyses"].map((x, i) => <button key={x} type="button" className={`filter-chip ${i === 0 ? "filter-chip-active" : ""}`}>{x}</button>)}</div>{filters && <div className="mt-4 grid gap-5 border-y bg-secondary/60 p-5 md:grid-cols-3"><label className="text-sm"><span className="meta-label mb-2 block">Publication date</span><select className="h-9 w-full rounded-md border bg-background px-2"><option>Any time</option><option>Since 2020</option><option>Since 2015</option></select></label><div><span className="meta-label mb-2 block">Study type</span><div className="grid gap-2">{TYPES.map((t) => <label key={t} className="flex items-center gap-2 text-sm"><Checkbox />{t}</label>)}</div></div><div className="grid gap-3"><label><span className="meta-label mb-2 block">Research field</span><Input placeholder="e.g. Neuroscience" /></label><label><span className="meta-label mb-2 block">Population</span><Input placeholder="e.g. Older adults" /></label></div></div>}</div>;
}
