import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BookOpenText, CheckCircle2, Circle, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { SearchForm } from "@/components/evidence/SearchForm";
import { adaptPaper, createAnswer } from "@/lib/evidence-model";
import { searchPapers } from "@/lib/research.functions";
import { saveResearch } from "@/lib/research-session";
export const Route=createFileRoute("/app/")({validateSearch:(s:Record<string,unknown>)=>({q:typeof s.q==="string"?s.q:""}),head:()=>({meta:[{title:"Search — Evidence"},{name:"description",content:"Search scientific literature and synthesize evidence."},{property:"og:title",content:"Search — Evidence"},{property:"og:description",content:"Search scientific literature and synthesize evidence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:SearchPage});
const suggestions=["Does caffeine improve memory?","How effective is cognitive behavioral therapy for insomnia?","Does resistance training improve bone density?"];
const stages=["Understanding question","Searching literature","Ranking evidence","Writing answer"];
function SearchPage(){const {q}=Route.useSearch();const search=useServerFn(searchPapers);const nav=useNavigate();const[busy,setBusy]=useState(false);const[stage,setStage]=useState(0);const[error,setError]=useState("");const run=async(query:string)=>{setBusy(true);setError("");for(let i=0;i<3;i++){setStage(i);await new Promise(r=>setTimeout(r,260))}try{const found=await search({data:{question:query}});setStage(3);const answer=createAnswer(query,found.map(adaptPaper));saveResearch(answer);await nav({to:"/app/results/$id",params:{id:answer.id}})}catch(e){setError(e instanceof Error?e.message:"Search failed")}finally{setBusy(false)}};useEffect(()=>{if(q)void run(q)},[]);return <div className="mx-auto max-w-5xl px-5 py-12 lg:py-20"><div className="max-w-2xl"><div className="mb-6 flex size-10 items-center justify-center border bg-secondary"><BookOpenText className="size-5 text-primary"/></div><p className="meta-label text-primary">New research</p><h1 className="mt-3 font-serif text-4xl sm:text-5xl">What do you want to understand?</h1><p className="mt-4 text-muted-foreground">Ask a focused question. Evidence will search, retrieve, synthesize, and connect every claim to a paper.</p></div><div className="mt-10"><SearchForm initial={q} busy={busy} onSearch={run}/></div>{busy&&<div className="mt-10 border-y py-6"><div className="grid gap-3 sm:grid-cols-4">{stages.map((x,i)=><div key={x} className={`flex items-center gap-2 text-sm ${i<=stage?"text-foreground":"text-muted-foreground"}`}>{i<stage?<CheckCircle2 className="size-4 text-success"/>:i===stage?<Loader2 className="size-4 animate-spin text-primary"/>:<Circle className="size-4"/>}{x}</div>)}</div></div>}{error&&<p role="alert" className="mt-6 border border-destructive/40 p-4 text-sm text-destructive">{error}</p>}<div className="mt-16 border-t pt-8"><p className="meta-label">Suggested questions</p><div className="mt-4 divide-y border-y">{suggestions.map(q=><button key={q} onClick={()=>void run(q)} className="flex w-full items-center justify-between py-4 text-left font-serif text-lg hover:text-primary">{q}<span>→</span></button>)}</div></div></div>}
