import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ArrowRight, CheckCircle2, Circle, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { SearchForm } from "@/components/evidence/SearchForm";
import { adaptPaper, createAnswer } from "@/lib/evidence-model";
import { searchPapers } from "@/lib/research.functions";
import { saveResearch } from "@/lib/research-session";
export const Route=createFileRoute("/app/")({validateSearch:(s:Record<string,unknown>):{q?:string}=>(typeof s["q"]==="string"&&s["q"]?{q:s["q"]}:{}),head:()=>({meta:[{title:"Search — Evidence"},{name:"description",content:"Search scientific literature and synthesize evidence."},{property:"og:title",content:"Search — Evidence"},{property:"og:description",content:"Search scientific literature and synthesize evidence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:SearchPage});
const suggestions=["Does caffeine improve memory?","How effective is cognitive behavioral therapy for insomnia?","Does resistance training improve bone density?"];
const stages=["Understanding question","Searching literature","Ranking evidence","Writing answer"];
function SearchPage(){const {q=""}=Route.useSearch();const search=useServerFn(searchPapers);const nav=useNavigate();const[busy,setBusy]=useState(false);const[stage,setStage]=useState(0);const[error,setError]=useState("");const run=async(query:string)=>{setBusy(true);setError("");for(let i=0;i<3;i++){setStage(i);await new Promise(r=>setTimeout(r,260))}try{const found=await search({data:{question:query}});setStage(3);const answer=createAnswer(query,found.map(adaptPaper));saveResearch(answer);await nav({to:"/app/results/$id",params:{id:answer.id}})}catch(e){setError(e instanceof Error?e.message:"Search failed")}finally{setBusy(false)}};useEffect(()=>{if(q)void run(q)},[]);return <div className="max-w-4xl px-4 py-8 sm:px-6 lg:px-10 lg:py-12"><div className="max-w-2xl"><p className="meta-label text-primary">New research</p><h1 className="mt-2 font-serif text-[2rem] leading-tight sm:text-4xl lg:text-[2.875rem]">What do you want to understand?</h1><p className="mt-3 text-muted-foreground">Ask a focused question. Evidence will search, retrieve, synthesize, and connect every claim to a paper.</p></div><div className="mt-7"><SearchForm initial={q} busy={busy} onSearch={run}/></div>{busy&&<div className="mt-8 border-y py-5" aria-live="polite"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stages.map((x,i)=><div key={x} className={`flex items-center gap-2 text-sm ${i<=stage?"text-foreground":"text-muted-foreground"}`}>{i<stage?<CheckCircle2 className="size-4 text-success"/>:i===stage?<Loader2 className="size-4 animate-spin text-primary"/>:<Circle className="size-4"/>}{x}</div>)}</div></div>}{error&&<p role="alert" className="mt-6 border border-destructive/40 p-4 text-sm text-destructive">{error}</p>}<section className="mt-12" aria-labelledby="suggested-heading"><h2 id="suggested-heading" className="meta-label">Suggested questions</h2><ul className="mt-3 divide-y border bg-card">{suggestions.map(s=><li key={s}><button type="button" disabled={busy} onClick={()=>void run(s)} className="group flex w-full items-center justify-between gap-4 px-4 py-3.5 text-left transition-colors hover:bg-surface-muted focus-visible:bg-surface-muted focus-visible:outline-none disabled:opacity-60"><span className="font-serif text-[1.0625rem] leading-snug">{s}</span><ArrowRight aria-hidden className="size-4 shrink-0 text-ink-muted transition-colors group-hover:text-primary"/></button></li>)}</ul></section></div>}
