import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Folder, Plus, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ResearchPaperCard } from "@/components/evidence/ResearchPaperCard";
import { createCollection, deleteCollection, listLibrary, removeSavedPaper } from "@/lib/library.functions";
import type { ResearchPaper } from "@/lib/evidence-model";
export const Route=createFileRoute("/app/library")({head:()=>({meta:[{title:"Library — Evidence"},{name:"description",content:"Saved papers and research collections."},{property:"og:title",content:"Library — Evidence"},{property:"og:description",content:"Saved papers and research collections."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:LibraryPage});
function LibraryPage(){const fetcher=useServerFn(listLibrary);const add=useServerFn(createCollection);const del=useServerFn(deleteCollection);const remove=useServerFn(removeSavedPaper);const[data,setData]=useState<{papers:Array<{id:string;paper_data:unknown}>;collections:Array<{id:string;name:string;description:string}>}>({papers:[],collections:[]});const[name,setName]=useState("");const[error,setError]=useState("");const load=useCallback(async()=>{try{setData(await fetcher({}) as typeof data)}catch{setError("Sign in to use your private research library.")}},[fetcher]);useEffect(()=>{void load()},[load]);return <div className="mx-auto max-w-6xl px-5 py-10"><p className="meta-label text-primary">Your research</p><h1 className="mt-3 font-serif text-4xl">Library</h1>{error&&<p className="mt-5 border p-4 text-sm text-muted-foreground">{error}</p>}<section id="collections" className="mt-10 scroll-mt-20"><div className="flex items-end justify-between"><div><p className="meta-label">Collections</p><h2 className="mt-2 font-serif text-2xl">Organize your work</h2></div></div><form onSubmit={async e=>{e.preventDefault();if(!name.trim())return;await add({data:{name}});setName("");void load()}} className="mt-5 flex max-w-md gap-2"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="New collection name"/><Button><Plus/>Create</Button></form><div className="mt-5 grid gap-px border bg-border sm:grid-cols-2 lg:grid-cols-3">{data.collections.map(c=><div key={c.id} className="flex items-center gap-3 bg-background p-5"><Folder className="text-primary"/><div className="flex-1"><p className="font-medium">{c.name}</p><p className="text-xs text-muted-foreground">Collection</p></div><Button variant="ghost" size="icon" onClick={async()=>{await del({data:{id:c.id}});void load()}} aria-label={`Delete ${c.name}`}><Trash2/></Button></div>)}{data.collections.length===0&&<p className="bg-background p-6 text-sm text-muted-foreground">No collections yet.</p>}</div></section><section id="saved" className="mt-14 scroll-mt-20"><p className="meta-label">Saved papers</p><h2 className="mt-2 font-serif text-2xl">Papers you kept</h2><div className="mt-5 space-y-4">{data.papers.map(row=>{const paper=row.paper_data as ResearchPaper;return <div key={row.id}><ResearchPaperCard paper={paper}/><Button variant="ghost" size="sm" onClick={async()=>{await remove({data:{id:row.id}});void load()}}><Trash2/>Remove</Button></div>})}{data.papers.length===0&&<div className="border-y py-10 text-sm text-muted-foreground">Save a paper from any results page and it will appear here.</div>}</div></section></div>}
