import { Link, useRouterState } from "@tanstack/react-router";
import { BookMarked, ChevronDown, Clock3, Compass, FolderClosed, HelpCircle, Library, Menu, Plus, Search, Settings, TrendingUp } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";
const nav=[{to:"/app",label:"Recent",icon:Search},{to:"/app/history",label:"History",icon:Clock3},{to:"/app/library",label:"Saved papers",icon:BookMarked},{to:"/app/library",label:"Collections",icon:FolderClosed},{to:"/app/topics",label:"Topics",icon:Compass},{to:"/app/topics",label:"Research trends",icon:TrendingUp}] as const;
function Sidebar({close}:{close?:()=>void}){const path=useRouterState({select:s=>s.location.pathname});return <div className="flex h-full flex-col bg-sidebar p-3"><Button asChild className="w-full justify-start"><Link to="/app" onClick={close}><Plus/>New research</Link></Button><div className="mt-6 space-y-5"><div><p className="meta-label px-2">Search</p>{nav.slice(0,2).map(x=><Link key={x.label} to={x.to} onClick={close} className={cn("sidebar-link",path===x.to&&"sidebar-link-active")}><x.icon/>{x.label}</Link>)}</div><div><p className="meta-label px-2">Library</p>{nav.slice(2,4).map(x=><Link key={x.label} to={x.to} onClick={close} className={cn("sidebar-link",path===x.to&&"sidebar-link-active")}><x.icon/>{x.label}</Link>)}</div><div><p className="meta-label px-2">Discover</p>{nav.slice(4).map(x=><Link key={x.label} to={x.to} onClick={close} className="sidebar-link"><x.icon/>{x.label}</Link>)}</div><div><p className="meta-label px-2">Your collections</p>{["Nutrition","AI","Education","Psychology"].map(x=><Link key={x} to="/app/library" onClick={close} className="sidebar-link"><span className="size-2 rounded-sm border bg-card"/>{x}</Link>)}</div></div><Link to="/app/settings" onClick={close} className="sidebar-link mt-auto"><Settings/>Settings</Link></div>}
export function AppShell({children}:{children:ReactNode}){const {session}=useAuth();const [open,setOpen]=useState(false);const initial=(session?.user.email??"R").slice(0,1).toUpperCase();return <div className="min-h-screen bg-surface"><header className="fixed inset-x-0 top-0 z-40 flex h-15 items-center border-b bg-background px-4 lg:px-6"><div className="flex w-60 items-center gap-3"><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Open sidebar"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-72 p-0"><SheetTitle className="sr-only">Workspace navigation</SheetTitle><Sidebar close={()=>setOpen(false)}/></SheetContent></Sheet><Link to="/app" className="font-serif text-xl font-semibold">Evidence</Link></div><nav className="hidden flex-1 items-center gap-5 lg:flex"><Link to="/app" className="top-link"><Search/>Search</Link><Link to="/app/library" className="top-link"><Library/>Library</Link><Link to="/app/topics" className="top-link"><Compass/>Topics</Link><Link to="/app/help" className="top-link"><HelpCircle/>Help</Link></nav><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="ml-auto gap-2 px-2"><span className="grid size-7 place-items-center rounded-full bg-foreground text-xs text-primary-foreground">{initial}</span><ChevronDown className="size-3"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-48"><DropdownMenuItem asChild><Link to="/app/settings">Account settings</Link></DropdownMenuItem><DropdownMenuSeparator/>{session?<DropdownMenuItem onSelect={()=>void supabase.auth.signOut()}>Sign out</DropdownMenuItem>:<DropdownMenuItem asChild><Link to="/sign-in">Sign in</Link></DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></header><aside className="fixed inset-y-0 left-0 top-15 hidden w-60 border-r lg:block"><Sidebar/></aside><main className="pt-15 lg:pl-60">{children}</main></div>}
